#!/usr/bin/env bash
# Scripts/test_check_file_length.sh
#
# Self-test for Scripts/check_file_length.sh, run before the gate it
# validates.
#
# forsgren's own (forsgren#1, ladder step 21): MenoPower's
# Scripts/go/check_file_length.py, which the gate ports, has no self-test.
# Its rules, which the cases below pin:
#   - Go production files only: a _test.go file is not judged (MenoPower's
#     default; it never passes --include-tests for Go).
#   - a generated file is judged like any other: MenoPower has no
#     generated-file exemption.
#   - a line is counted as Python counts it, so a last line without a
#     newline counts (wc -l would not count it).
#   - more than the limit is red, the limit itself is green.
# forsgren's rules on top:
#   - the files are the module's own, as `go list ./...` sees them, so a
#     directory go.mod ignores (node_modules) is never judged, and a file
#     another GOOS builds is.
#   - a module with no production .go file is red: a scan over nothing is no
#     pass (MenoPower prints its OK line for it).
#
#   1. a 601-line production file                 -> exit 1, naming it, 601
#   2. a 600-line production file                 -> exit 0
#   3. 700-line _test.go files (one GOOS-bound)   -> exit 0
#   4. a 700-line generated file                  -> exit 1, naming it
#   5. 600 lines plus a last line with no newline -> exit 1, 601 lines
#   6. a 700-line file only another GOOS builds   -> exit 1, naming it
#   7. a 700-line .go file under node_modules,
#      which go.mod ignores                       -> exit 0
#   8. a module with no .go file                  -> exit 1, with the reason
#   9. a root directory that does not exist       -> exit 2
#  10. MUTATION PROOF: the gate with `-gt` turned into `-ge` is red on
#      case 2, naming its file at 600 lines: the comparison is what puts the
#      limit itself on the green side
#  11. MUTATION PROOF: case 7 with go.mod's `ignore node_modules` line
#      removed is red, naming the node_modules file: go.mod's ignore, not a
#      path rule in the gate, is what keeps node_modules out, and case 7's
#      green is not vacuous
#  12. MUTATION PROOF: the gate with IgnoredGoFiles dropped from its
#      FIELDS line (the `go list` file lists it reads) is green on case 6: that field is what brings a
#      file another GOOS builds into the count

set -euo pipefail

cd "$(dirname "$0")/.." || exit 1

GATE="./Scripts/check_file_length.sh"
LIMIT=600

# shellcheck source=Scripts/lib_selftest.sh
source Scripts/lib_selftest.sh
selftest_begin "file-length gate self-test"

[[ -x "$GATE" ]] || selftest_abort "the file-length gate ${GATE} is missing (or not executable): nothing holds Go production files to ${LIMIT} lines"

# run_gate <gate> <module> — sets RC and OUT (stdout and stderr together).
run_gate() {
  capture "$1" "$2" "$LIMIT"
}
# new_module <name> — an empty module that ignores node_modules, as
# forsgren's go.mod does.
new_module() {
  MOD="${TMP}/$1"
  mkdir -p "$MOD"
  printf 'module example.com/%s\n\ngo 1.26.1\n\nignore node_modules\n' "$1" > "${MOD}/go.mod"
}

# write_go <relative-path> <lines> [first-line] — a valid Go file of exactly
# <lines> newline-terminated lines: the optional first line, the package
# clause, then comment lines.
write_go() {
  local path="${MOD}/$1" lines="$2" first="${3:-}"
  mkdir -p "$(dirname "$path")"
  {
    if [[ -n "$first" ]]; then
      printf '%s\n' "$first"
      lines=$((lines - 1))
    fi
    printf 'package m\n'
    local i
    for ((i = 2; i <= lines; i++)); do
      printf '// filler line %d\n' "$i"
    done
  } > "$path"
}

# --- Case 1: one line over the limit.
new_module "over"
write_go "lib.go" 601
run_gate "$GATE" "$MOD"
want_exit "a 601-line production file is red, naming it and its count" 1 "lib.go: 601 lines"

# --- Case 2: exactly the limit.
new_module "at-limit"
write_go "lib.go" 600
run_gate "$GATE" "$MOD"
want_exit "a 600-line production file is green" 0 "OK:"
AT_LIMIT="$MOD"

# --- Case 3: long test files, one of them bound to another GOOS.
new_module "long-tests"
write_go "lib.go" 10
write_go "big_test.go" 700
write_go "big_windows_test.go" 700
run_gate "$GATE" "$MOD"
want_exit "700-line _test.go files are not judged" 0 "OK:"

# --- Case 4: a generated file has no exemption.
new_module "generated"
write_go "lib.go" 10
write_go "zz_generated.go" 700 "// Code generated by the fixture. DO NOT EDIT."
run_gate "$GATE" "$MOD"
want_exit "a 700-line generated file is red, naming it" 1 "zz_generated.go: 700 lines"

# --- Case 5: a last line with no newline still counts.
new_module "no-final-newline"
write_go "lib.go" 600
printf '// the last line, no newline' >> "${MOD}/lib.go"
run_gate "$GATE" "$MOD"
want_exit "600 lines plus an unterminated last line is 601, red" 1 "lib.go: 601 lines"

# --- Case 6: a file only another GOOS builds is still production code.
new_module "other-goos"
write_go "lib.go" 10
write_go "big_windows.go" 700
run_gate "$GATE" "$MOD"
want_exit "a 700-line file only windows builds is red, naming it" 1 "big_windows.go: 700 lines"
OTHER_GOOS="$MOD"

# --- Case 7: node_modules, which go.mod ignores.
new_module "node-modules"
write_go "lib.go" 10
write_go "node_modules/flatted/golang/big.go" 700
run_gate "$GATE" "$MOD"
want_exit "a 700-line .go file under the ignored node_modules is not judged" 0 "OK:"
NODE_MODULES="$MOD"

# --- Case 8: no Go file at all.
new_module "empty"
run_gate "$GATE" "$MOD"
want_exit "a module with no .go file is red" 1 "no production .go file"

# --- Case 9: a root directory that does not exist.
run_gate "$GATE" "${TMP}/nope"
want_exit "a missing root directory is a tooling error" 2 "root directory not found"

# --- Case 10: MUTATION PROOF. -gt turned into -ge.
MUTANT="${TMP}/mutant-ge/Scripts/check_file_length.sh"
if selftest_mutant "$GATE" "$MUTANT" 's/ -gt / -ge /'; then
  run_gate "$MUTANT" "$AT_LIMIT"
  want_exit "mutation: with -ge instead of -gt, case 2 is red at 600 lines" 1 "lib.go: 600 lines"
fi

# --- Case 11: MUTATION PROOF. go.mod without its ignore line.
sed '/^ignore node_modules$/d' "${NODE_MODULES}/go.mod" > "${TMP}/go.mod.mutant"
if cmp -s "${NODE_MODULES}/go.mod" "${TMP}/go.mod.mutant"; then
  fail "the mutation changed nothing: no ignore line in the fixture go.mod"
else
  mv "${TMP}/go.mod.mutant" "${NODE_MODULES}/go.mod"
  run_gate "$GATE" "$NODE_MODULES"
  want_exit "mutation: without go.mod's ignore, case 7 is red, naming the node_modules file" 1 "node_modules/flatted/golang/big.go: 700 lines"
fi

# --- Case 12: MUTATION PROOF. IgnoredGoFiles dropped from the template.
MUTANT="${TMP}/mutant-ignored/Scripts/check_file_length.sh"
if selftest_mutant "$GATE" "$MUTANT" '/^FIELDS=/s/ IgnoredGoFiles//'; then
  run_gate "$MUTANT" "$OTHER_GOOS"
  want_exit "mutation: without IgnoredGoFiles, case 6 is green" 0 "OK:"
fi

selftest_end "the file-length gate does not tell green from red" \
  "file-length gate is red over ${LIMIT} lines (a generated file, a file another GOOS builds and an unterminated last line included) and on no .go file, green at ${LIMIT} and on long test files and node_modules, a tooling error on a missing root, and its comparison, go.mod's ignore and IgnoredGoFiles are what decide those cases"
